const SHIPMENTS_PREFIX = "shipments/fetchAll";

export const SHIPMENTS_INIT = `${SHIPMENTS_PREFIX}/SHIPMENTS_INIT`;
export const SHIPMENTS_PENDING = `${SHIPMENTS_PREFIX}/SHIPMENTS_PENDING`;
export const SHIPMENTS_SUCCESS = `${SHIPMENTS_PREFIX}/SHIPMENTS_SUCCESS`;
export const SHIPMENTS_FAIL = `${SHIPMENTS_PREFIX}/SHIPMENTS_FAIL`;

const SHIPMENT_PREFIX = "shipment/fetch";

export const SHIPMENT_INIT = `${SHIPMENT_PREFIX}/SHIPMENT_INIT`;
export const SHIPMENT_PENDING = `${SHIPMENT_PREFIX}/SHIPMENT_PENDING`;
export const SHIPMENT_SUCCESS = `${SHIPMENT_PREFIX}/SHIPMENT_SUCCESS`;
export const SHIPMENT_FAIL = `${SHIPMENT_PREFIX}/SHIPMENT_FAIL`;

const SHIPMENT_UPDATE_PREFIX = "shipment/update";

export const SHIPMENT_UPDATE_INIT = `${SHIPMENT_UPDATE_PREFIX}/SHIPMENT_UPDATE_INIT`;
export const SHIPMENT_UPDATE_PENDING = `${SHIPMENT_UPDATE_PREFIX}/SHIPMENT_UPDATE_PENDING`;
export const SHIPMENT_UPDATE_SUCCESS = `${SHIPMENT_UPDATE_PREFIX}/SHIPMENT_UPDATE_SUCCESS`;
export const SHIPMENT_UPDATE_FAIL = `${SHIPMENT_UPDATE_PREFIX}/SHIPMENT_UPDATE_FAIL`;
